name: CI

on: 
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    schedule:
      - cron: '20 9 4 * *' # Monthly builds

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install rabbitmq for tests
      run: |
        sudo apt update && sudo apt install -y rabbitmq-server
        sudo systemctl stop rabbitmq-server

    - name: Install dependencies
      run: |
        pip install .[dev]

    - name: Test with pytest
      run: |
        pytest
